"""
app/models/base.py

Shared SQLAlchemy model mixins used by all database models.

Provides:
  - `UUIDMixin`: Adds a UUID primary key generated server-side by PostgreSQL.
  - `TimestampMixin`: Adds `created_at` and `updated_at` timestamps with auto-management.
"""

import uuid

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class UUIDMixin:
    """
    Adds a UUID primary key to any SQLAlchemy model.
    UUIDs are generated by the PostgreSQL server using gen_random_uuid().
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """
    Adds `created_at` and `updated_at` with server-generated timestamps.
    All timestamps are stored in UTC with timezone info.
    `updated_at` auto-updates on every record modification.
    """

    created_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
