"""
app/models/recommendation.py

Recommendation database model.
"""

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.session import EmotionSession


class Recommendation(UUIDMixin, TimestampMixin, Base):
    """
    recommendations table.
    Stores dynamic actionable recommendations generated by AI coaches for sessions.
    """

    __tablename__ = "recommendations"

    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("emotion_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    recommendation: Mapped[str] = mapped_column(String(1000), nullable=False)

    # Relationship
    session: Mapped["EmotionSession"] = relationship("EmotionSession", back_populates="recommendation_list")

    def __repr__(self) -> str:
        return f"<Recommendation id={self.id} session_id={self.session_id}>"
