"""
app/models/tone_report.py

ToneReport database model.
Stores the results of a premium AI tone coaching session analysis.
Each report belongs to a user and optionally links to an EmotionSession.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import DateTime, Float, ForeignKey, JSON, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.session import EmotionSession


class ToneReport(UUIDMixin, TimestampMixin, Base):
    """
    tone_reports table.
    Generated by the AI tone coaching engine after a premium session.
    Stores all computed scores and AI-generated recommendations.
    """

    __tablename__ = "tone_reports"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("emotion_sessions.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Core scores (0-100)
    overall_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    tone_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    delivery_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    energy_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pace_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    hesitation_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    consistency_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # AI-generated coaching content (stored as JSON arrays)
    recommendations: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    strengths: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    improvement_areas: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)

    # Raw audio metrics from browser (stored as JSON object)
    raw_audio_metrics: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="tone_reports")

    def __repr__(self) -> str:
        return f"<ToneReport id={self.id} user_id={self.user_id} score={self.overall_score}>"
